name: Release Package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      enabledTest:
        description: "Select whether the package should be tested"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"
      enabledUpload:
        description: "Select whether the package should be uploaded"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Build Requirements
        run: python3 -m pip install --upgrade poetry
      - name: Build
        run: python3 -m poetry build
  test:
    runs-on: ubuntu-latest
    if: "${{ inputs.enabledTest }}" == "true"
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Build Requirements
        run: python3 -m pip install --upgrade poetry pytest
      - name: Test
        run: python3 -m poetry run pytest tests/unit
  upload:
    runs-on: ubuntu-latest
    if: "${{ inputs.enabledUpload }}" == "true"
    needs: [build, test]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Build Requirements
        run: python3 -m pip install --upgrade twine
      - name: Upload
        run: python3 -m twine upload --non-interactive -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PWD }} --repository-url https://pypi.org/ dist/*
