name: Release Package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      enabledTest:
        description: "Select whether the package should be tested"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      enabledUpload:
        description: "Select whether the package should be uploaded"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

env:
  ENABLED_TEST: ${{ github.event.inputs.enabledTest || "false" }}
  ENABLED_UPLOAD: ${{ github.event.inputs.enabledUpload || "true" }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Build Requirements
        run: python3 -m pip install --upgrade poetry twine argparse pytest
      - name: Build, Test, Upload
        run: python3 cicd.py --test ${{ env.ENABLED_TEST }} --upload ${{ env.ENABLED_UPLOAD }} -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PWD }}
